Use lower heartbeat timeout to allow spot instances to terminate more quickly
giantswarm/cluster-standup-teardown pull request #173
Opened 2024-12-10 17:42 UTC by AndiDog

Related to https://github.com/giantswarm/aws-nth-crossplane-resources/pull/7, towards https://github.com/giantswarm/giantswarm/issues/31843

### What does this PR do?

See comment in code. Tests would time out if we don't specify this together with EC2 Spot instance usage.

### Checklist

- [x] CHANGELOG.md has been updated

2024-12-10 17:44 UTC, Gacko approved these changes

2024-12-11 11:59 UTC, fiunchinho requested changes
I'd drope a note in the changelog.

2024-12-11 12:31 UTC, AndiDog commented
> I'd drope a note in the changelog.

True, forgot that despite ticking the checkbox 😆. Done.

2024-12-11 13:23 UTC, merged

2025-01-06 07:25 UTC, AverageMarcus commented
@AndiDog Could you please make sure that there is an issue (or task on an existing issue) to remove this value once the upstream is fixed?

2025-01-07 12:40 UTC, AndiDog commented
Referenced in https://github.com/giantswarm/giantswarm/issues/32232 so we revert this at some point